services:
  - type: web
    name: tcc-api
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tcc-db
          property: connectionString
      - key: ALLOW_ORIGINS
        value: '["*"]'
      - key: MODEL_PATH
        value: model/rf_model.pkl
      - key: ENCODER_PATH
        value: model/label_encoder.pkl
      - key: DATASET_PATH
        value: model/dataset/malicious_phish.csv
      - key: METRICS_PATH
        value: model/metrics.json

databases:
  - name: tcc-db
    plan: free
